version: "3.7"

services:
    backend:
        build: 
            context: ./backend
        image: node:12-alpine
        ports:
            - 3000:3000
        
    frontend:
        build: 
            context: ./frontend
        image: node:12-alpine
        ports:
            - 3001:3000