# Dockerfile for building the website front end
# following https://www.dailysmarty.com/posts/steps-for-deploying-a-static-html-site-with-docker-and-nginx
FROM nginx:alpine
COPY . /usr/share/nginx/html